version: 2.1 

executors:
  default:
    working_directory: ~/workspace
    docker:
      - image: circleci/node:8.11.4

jobs:
  firebase:
    executor:
      name: default
    
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "reactjs/package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm run install:all:ci

      - run:
          name: 'Install Dependecies'
          command: npm install --save-dev firebase-tools

      - save_cache:
          paths:
            - node_modules
            - reactjs/node_modules
          key: v1-dependencies-{{ checksum "reactjs/package.json" }}

      - run:
          name: 'Build(development)'
          working_directory: reactjs
          command: REACT_APP_ENV=development npm run build
          
      - run:
          name: 'Deploy to Hosting(development6)'
          working_directory: reactjs
          command: ../node_modules/.bin/firebase deploy --only hosting  -P development --token "$FIREBASE_TOKEN"

      - run:
          name: 'Build(Production)'
          working_directory: reactjs
          command: REACT_APP_ENV=production npm run build
          
      - run:
          name: 'Deploy to Hosting(Production)'
          working_directory: reactjs
          command: ../node_modules/.bin/firebase deploy --only hosting  -P production --token "$FIREBASE_TOKEN"

workflows:
  deploy:
    jobs:
      - firebase
      filters:
        branches:
          only: master            
