export const SET_USER_INFO = 'SET_USER_INFO';
export const SET_OGP_INFO = 'SET_OGP_INFO';
export const RESET_OGP_INFO = 'RESET_OGP_INFO';

// challenge
export const FETCH_CHALLENGES_REQUEST = 'FETCH_CHALLENGES_REQUEST';
export const FETCH_CHALLENGES_SUCCESS = 'FETCH_CHALLENGES_SUCCESS';
export const FETCH_CHALLENGES_ERROR = 'FETCH_CHALLENGES_ERROR';

// category
export const FETCH_CATEGORIES_REQUEST = 'FETCH_CATEGORIES_REQUEST';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_ERROR = 'FETCH_CATEGORIES_ERROR';
