// ogp
export const SET_OGP_INFO = 'SET_OGP_INFO';
export const RESET_OGP_INFO = 'RESET_OGP_INFO';

// giphy
export const SHOW_GIPHY = 'SHOW_GIPHY';
export const HIDE_GIPHY = 'HIDE_GIPHY';

// sensitive
export const SHOW_SENSITIVE = 'SHOW_SENSITIVE';
export const HIDE_SENSITIVE = 'HIDE_SENSITIVE';

// secirites
export const FETCH_MUTES_REQUEST = 'FETCH_MUTES_REQUEST';
export const FETCH_MUTES_SUCCESS = 'FETCH_MTUES_SUCCESS';
export const FETCH_MUTES_ERROR = 'FETCH_MUTES_ERROR';
export const FETCH_BLOCKS_REQUEST = 'FETCH_BLOCKS_REQUEST';
export const FETCH_BLOCKS_SUCCESS = 'FETCH_BLOCKS_SUCCESS';
export const FETCH_BLOCKS_ERROR = 'FETCH_BLOCKS_ERROR';

// challenge
export const RESET_CHALLENGE_INFO = 'RESET_CHALLENGE_INFO';
export const FETCH_CHALLENGES_REQUEST = 'FETCH_CHALLENGES_REQUEST';
export const FETCH_CHALLENGES_SUCCESS = 'FETCH_CHALLENGES_SUCCESS';
export const FETCH_CHALLENGES_ERROR = 'FETCH_CHALLENGES_ERROR';
export const FETCH_CHALLENGE_REQUEST = 'FETCH_CHALLENGE_REQUEST';
export const FETCH_CHALLENGE_SUCCESS = 'FETCH_CHALLENGE_SUCCESS';
export const FETCH_CHALLENGE_ERROR = 'FETCH_CHALLENGE_ERROR';
export const FETCH_PINNED_CHALLENGES_REQUEST =
  'FETCH_PINNED_CHALLENGES_REQUEST';
export const FETCH_PINNED_CHALLENGES_SUCCESS =
  'FETCH_PINNED_CHALLENGES_SUCCESS';
export const FETCH_PINNED_CHALLENGES_ERROR = 'FETCH_PINNED_CHALLENGES_ERROR';

// category
export const RESET_CATEGORY_INFO = 'RESET_CATEGORY_INFO';
export const FETCH_CATEGORIES_REQUEST = 'FETCH_CATEGORIES_REQUEST';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_ERROR = 'FETCH_CATEGORIES_ERROR';
export const FETCH_CATEGORY_REQUEST = 'FETCH_CATEGORY_REQUEST';
export const FETCH_CATEGORY_SUCCESS = 'FETCH_CATEGORY_SUCCESS';
export const FETCH_CATEGORY_ERROR = 'FETCH_CATEGORY_ERROR';

// user
export const SET_USER_INFO = 'SET_USER_INFO';
export const RESET_USER_INFO = 'RESET_USER_INFO';
export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_ERROR = 'FETCH_USERS_ERROR';
export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_ERROR = 'FETCH_USER_ERROR';

// topic
export const RESET_TOPIC_INFO = 'RESET_TOPIC_INFO';
export const FETCH_TOPICS_REQUEST = 'FETCH_TOPICS_REQUEST';
export const FETCH_TOPICS_SUCCESS = 'FETCH_TOPICS_SUCCESS';
export const FETCH_TOPICS_ERROR = 'FETCH_TOPICS_ERROR';
export const FETCH_TOPIC_REQUEST = 'FETCH_TOPIC_REQUEST';
export const FETCH_TOPIC_SUCCESS = 'FETCH_TOPIC_SUCCESS';
export const FETCH_TOPIC_ERROR = 'FETCH_TOPIC_ERROR';
