// 記録戦略
export const RECORD_STRATEGY_SIMPLE = 'RECORD_STRATEGY_SIMPLE';
export const RECORD_STRATEGY_MULTI = 'RECORD_STRATEGY_MULTI';
export const RECORD_STRATEGY_RESET = 'RECORD_STRATEGY_RESET';
export const RECORD_STRATEGY_MULTI_RESET = 'RECORD_STRATEGY_MULTI_RESET';
