// 記録戦略
export const RECORD_STRATEGY_SIMPLE = 'RECORD_STRATEGY_SIMPLE';
export const RECORD_STRATEGY_MULTI = 'RECORD_STRATEGY_MULTI';
export const RECORD_STRATEGY_RESET = 'RECORD_STRATEGY_RESET';

// 記録オプション
export const RECORD_OPTION_NONE = 'RECORD_OPTION_NONE';
export const RECORD_OPTION_TIME = 'RECORD_OPTION_TIME';
